# Generated by Django 5.2.3 on 2025-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
