# Generated by Django 5.2.3 on 2025-06-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_alter_uploadedfile_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEncryptionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('tag', models.BinaryField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fileshare.uploadedfile')),
            ],
        ),
    ]
