# Generated by Django 5.2.3 on 2025-06-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0005_alter_uploadedfile_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
